<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);


/*** @var RBKmoney_Payform_Helper_Data $data */
$data = Mage::helper("payform");

$paymentFormCompanyName = $data->getPaymentFormCompanyName();
$companyName = !empty($paymentFormCompanyName) ? 'data-name="' . $paymentFormCompanyName . '"' : '';

$paymentFormButtonLabel = $data->getPaymentFormButtonLabel();
$buttonLabel = !empty($paymentFormButtonLabel) ? 'data-label="' . $paymentFormButtonLabel . '"' : '';

$paymentFormDescription = $data->getPaymentFormDescription();
$description = !empty($paymentFormDescription) ? 'data-description="' . $paymentFormDescription . '"' : '';

$paymentFormCssButton = $data->getPaymentFormCssButton();
$style = !empty($paymentFormCssButton) ? '<style>' . $paymentFormCssButton . '</style>' : '';

try {
    if(empty($_SESSION['order']) || $_SESSION['order']['id'] != $orderId) {
        $response = $data->createInvoice($order);

        $invoice_id = $response["invoice"]["id"];
        $invoice_access_token = $response["invoiceAccessToken"]["payload"];

        $_SESSION['order']['id'] = $orderId;
        $_SESSION['order']['invoice_id'] = $invoice_id;
        $_SESSION['order']['invoiceAccessToken'] = $invoice_access_token;
    } else {
        $invoice_id = $_SESSION['order']['invoice_id'];
        $invoice_access_token = $_SESSION['order']['invoiceAccessToken'];
    }

} catch (Exception $ex) {
    die($ex->getMessage());
}
?>
<h2><?php echo $this->__('RBKmoney payment') ?></h2>

<?php echo $style; ?>

<form action="<?php echo $data->getSuccessUrl(); ?>" method="POST">
    <script src="<?php echo $data::PAYMENT_FORM_URL; ?>" class="rbkmoney-checkout"
            data-invoice-id="<?php echo $invoice_id; ?>"
            data-invoice-access-token="<?php echo $invoice_access_token; ?>"
        <?php echo $companyName; ?>
        <?php echo $buttonLabel; ?>
        <?php echo $description; ?>
    >
    </script>
</form>
